name: Continuous Deployment

on:
  push:
    branches: [ master ]

jobs:
  powershell-tests:
    name: PowerShell Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Pester tests (pwsh)
        run: |
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.0.4 -confirm:$false -Force
          Invoke-Pester -Path ".\scripts" -Output Detailed -CI
        shell: pwsh

  finish:
    name: Finish
    needs: [ powershell-tests ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-ruby@v1
      - name: Notify DPT on Discord
        if: always()
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.DISCORD_DPT_DEPLOYMENT_NOTIFICATIONS_WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          git clone https://github.com/DiscordHooks/github-actions-discord-webhook webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        shell: bash
