name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  powershell-tests:
    name: PowerShell Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Run Pester tests (pwsh)
        run: |
          Write-host $PSVersionTable.PSVersion.Major $PSVersionTable.PSRemotingProtocolVersion.Minor
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.0.4 -confirm:$false -Force
          Invoke-Pester -Path ".\scripts" -Output Detailed -CI
        continue-on-error: false
        shell: pwsh

  generate-db:
    name: Generate dbs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: .xlsx -> .csv
        run: |
          python -V
          python ./scripts/xlsx2csv.py 'declensions & conjugations.xlsx' ./build --all
          ls -la ./build
        continue-on-error: false

      - name: inflections - .csv -> .sql
        run: |
          ./scripts/Generate-InflectionsSql.ps1
        continue-on-error: false
        shell: pwsh

      - name: inflections - .sql -> .db
        run: |
          cat ./build/inflections.sql | ./bin/linux/sqlite3
        continue-on-error: false

      - name: stems - .csv -> .sql
        run: |
          ./scripts/Generate-StemsSql.ps1
        continue-on-error: false
        shell: pwsh

      - name: stems - .sql -> .db
        run: |
          cat ./build/stems.sql | ./bin/linux/sqlite3
          ./bin/linux/sqlite3 ./build/stems.db '.dump _stems' | ./bin/linux/sqlite3 ./build/inflections.db
        continue-on-error: false

      - name: generate all words
        run: |
          curl https://apps.kitamstudios.com/inflections/all_words_gen -o ./build/all_words_gen -v
          chmod +x ./build/all_words_gen
          cp ./build/inflections.db ./build/inflections_all_words.db
          ./build/all_words_gen --inflection-db ./build/inflections_all_words.db

      - name: inflections - .db -> .zip
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -9 -j ./build/inflections.zip ./build/inflections.db

      - name: stems - .db -> .zip
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -9 -j ./build/stems.zip ./build/stems.db

      - name: all_words - .db -> .zip
        uses: montudor/action-zip@v0.1.1
        with:
          args: zip -9 -j ./build/inflections_all_words.zip ./build/inflections_all_words.db

      - name: Azure Login
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_KSAPPLICATIONS_STORAGE }}

      - name: Deploy
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
              az storage blob upload-batch --account-name ksapplications -d '$web/inflections' -s ./build

      - name: Azure Logout
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        run: |
              az logout

  finish:
    name: Finish
    needs: [ powershell-tests, generate-db ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-ruby@v1
      - name: Notify DPT on Discord
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        env:
          JOB_STATUS: ${{ job.status }}
          WEBHOOK_URL: ${{ secrets.DISCORD_DPT_DEPLOYMENT_NOTIFICATIONS_WEBHOOK_URL }}
          HOOK_OS_NAME: ${{ runner.os }}
          WORKFLOW_NAME: ${{ github.workflow }}
        run: |
          git clone https://github.com/DiscordHooks/github-actions-discord-webhook webhook
          bash webhook/send.sh $JOB_STATUS $WEBHOOK_URL
        shell: bash
